Repository Saransh-cpp/BookRentApp-Chapter3, pull requests merged in 2021-12, with the labels that each got.

#17 Update all the versions to latest available versions
  android/app/build.gradle
  android/build.gradle
  lib/Utility/auth.dart
  pubspec.lock
  pubspec.yaml
Labels: easy, CodePeak

#24 Add Labels
  .github/workflows/App.yml
Labels: ci, easy, CodePeak

#23 Renderflex overflow in home screen issue#20 solved
  lib/Screens/Home.dart
  lib/Screens/LoginPage.dart
Labels: good first issue, ui/ux, CodePeak

#26 Removed Wrapper.dart and database.dart
  lib/Screens/Home.dart
  lib/Screens/LoginPage.dart
  lib/Wrapper.dart
  lib/database.dart
  lib/main.dart
Labels: good first issue, redundant-code, SWoC

#44 Created pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, good first issue, CodePeak

#55 Add issue template
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: documentation, good first issue, CodePeak

#59 Remove line breaks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, good first issue, CodePeak

#57 add workflow for linting
  .github/workflows/App.yml
  .github/workflows/Test.push.yml
Labels: ci, moderate, CodePeak, SWoC

#64 Add badges
  README.md
Labels: documentation, good first issue, CodePeak

#65 add apk ci pipeline
  .github/workflows/Test.push.yml
Labels: ci, moderate, CodePeak

#66 added a splash screen issue #13
  android/app/src/main/res/drawable/chapter3_app_logo.png
  android/app/src/main/res/drawable/launch_background.xml
  images/chapter3Logo.png
  lib/Screens/splash.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: easy, CodePeak

#51 Make the UI of Register screen uniform #8 Issue Solved #25
  lib/Screens/Register.dart
Labels: moderate, ui/ux, refactor, CodePeak

#73 revamp allbooks screen
  lib/Widgets.dart
Labels: ui/ux, easy, CodePeak

#60 Linting all files in lib
  lib/QuizScreens/Question1.dart
  lib/QuizScreens/Question2.dart
  lib/QuizScreens/Question3.dart
  lib/QuizScreens/Question4.dart
  lib/QuizScreens/Question5.dart
  lib/QuizScreens/Question6.dart
  lib/QuizScreens/Question7.dart
  lib/QuizScreens/Question8.dart
  lib/QuizScreens/Question9.dart
  lib/QuizScreens/QuizResult.dart
  lib/Screens/AboutUs.dart
  lib/Screens/AdminSignIn.dart
  lib/Screens/AllBooks.dart
  lib/Screens/Favourites.dart
  lib/Screens/Home.dart
  lib/Screens/LoginPage.dart
  lib/Screens/NavBar.dart
  lib/Screens/Profile.dart
  lib/Screens/Register.dart
  lib/Screens/YourOrders.dart
  lib/Screens/allBooksofAGenre.dart
  lib/Screens/product_details.dart
  lib/Widgets.dart
  lib/main.dart
  lib/provider/user.dart
  lib/services/user.dart
Labels: moderate, SWoC

#80 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, good first issue, CodePeak

#70 Issue 02 readme add
  README.md
Labels: documentation, good first issue, CodePeak

#78 Issue 45 login without credentials
  lib/Screens/LoginPage.dart
Labels: help wanted, hard, CodePeak

#82 added Contact Us section , fixed issue #71
  lib/Screens/Contact.dart
Labels: enhancement, moderate, ui/ux

#86 improve deprecated syntax
  lib/QuizScreens/Question1.dart
  lib/QuizScreens/Question2.dart
  lib/QuizScreens/Question3.dart
  lib/QuizScreens/Question4.dart
  lib/QuizScreens/Question5.dart
  lib/QuizScreens/Question6.dart
  lib/QuizScreens/Question7.dart
  lib/QuizScreens/Question8.dart
  lib/QuizScreens/Question9.dart
  lib/QuizScreens/QuizResult.dart
  lib/Screens/AboutUs.dart
  lib/Screens/AdminSignIn.dart
  lib/Screens/AllBooks.dart
  lib/Screens/BestSellers.dart
  lib/Screens/Favourites.dart
  lib/Screens/Home.dart
  lib/Screens/Loading.dart
  lib/Screens/LoginPage.dart
  lib/Screens/NavBar.dart
  lib/Screens/Profile.dart
  lib/Screens/Recommendations.dart
  lib/Screens/Register.dart
  lib/Screens/YourOrders.dart
  lib/Screens/orders.dart
  lib/Screens/product_details.dart
  lib/Screens/product_search.dart
  lib/Widgets.dart
  lib/main.dart
  lib/model/QuizDataModel.dart
  lib/model/cart_item.dart
  lib/model/fav.dart
  lib/model/order.dart
  lib/model/product.dart
  lib/model/user.dart
  lib/provider/app.dart
  lib/provider/product.dart
  lib/provider/user.dart
  lib/services/order.dart
  lib/services/product.dart
  lib/services/user.dart
  pubspec.lock
Labels: redundant-code, easy, CodePeak, SWoC

#88 remove unnecessary imports
  lib/QuizScreens/Question1.dart
  lib/QuizScreens/Question2.dart
  lib/QuizScreens/Question3.dart
  lib/QuizScreens/Question4.dart
  lib/QuizScreens/Question5.dart
  lib/QuizScreens/Question6.dart
  lib/QuizScreens/Question7.dart
  lib/QuizScreens/Question8.dart
  lib/QuizScreens/Question9.dart
  lib/QuizScreens/QuizResult.dart
  lib/Screens/AllBooks.dart
  lib/Screens/Favourites.dart
  lib/Screens/Home.dart
  lib/Screens/LoginPage.dart
  lib/Screens/NavBar.dart
  lib/Screens/Profile.dart
  lib/Screens/Register.dart
  lib/Screens/YourOrders.dart
  lib/Screens/product_details.dart
  lib/Widgets.dart
  lib/provider/user.dart
  lib/services/user.dart
Labels: good first issue, redundant-code, CodePeak, SWoC

#90 Issue 87 portrait only
  lib/Screens/BestSellers.dart
  lib/Screens/Contact.dart
  lib/Screens/Recommendations.dart
  lib/main.dart
Labels: good first issue, ui/ux, CodePeak

#108 removed the warning regarding migration
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  pubspec.lock
Labels: bug, easy

#112 Fix error while running the project on android.
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  pubspec.lock
Labels: easy, CodePeak

#95 Issue 94 signing issues
  lib/Screens/LoginPage.dart
  lib/Screens/Register.dart
  lib/main.dart
Labels: bug, moderate, CodePeak
