Repository Saransh-cpp/BookRentApp-Chapter3, pull requests merged in 2022-01, with the labels that each got.

#100 Issue 92 weird app behavior
  lib/Screens/Favourites.dart
  lib/Screens/YourOrders.dart
  lib/Screens/product_details.dart
  pubspec.lock
Labels: bug, hard, CodePeak

#83 Improved YourCart section with new features
  images/emptycart.png
  lib/Screens/YourOrders.dart
  pubspec.yaml
Labels: ui/ux, hard, CodePeak

#122 Issue 21 drawer
  fonts/Montserrat-Bold.ttf
  fonts/Montserrat-Regular.ttf
  images/drawer-back.png
  lib/Screens/Home.dart
  pubspec.yaml
Labels: ui/ux, refactor, hard, CodePeak

#131 fixes: #115 fixed renderflex overflow
  lib/Screens/your_orders.dart
Labels: good first issue, ui/ux, SWoC

#125 Add correct parent widget
  lib/Screens/contact.dart
Labels: moderate, ui/ux, SWoC

#140 Fixes deprecation of splash screen
  android/app/src/main/AndroidManifest.xml
  pubspec.lock
Labels: easy, SWoC
